### ISSUE TITLE
Line continuation tests

### ISSUE THREAD

**Issue by certik** [marshallward/flint#11]
Here are some tough line continuation tests:

https://gitlab.com/lfortran/lfortran/-/blob/a1fe312c323d894aab45323ccf33a93d1fb6d098/integration_tests/line_continuation_01.f90

https://gitlab.com/lfortran/lfortran/-/blob/a1fe312c323d894aab45323ccf33a93d1fb6d098/integration_tests/line_continuation_02.f90

https://gitlab.com/lfortran/lfortran/-/blob/a1fe312c323d894aab45323ccf33a93d1fb6d098/integration_tests/line_continuation_03.f90

**Comment by marshallward** [comment]
Flint debug output shown below.

Looks like it's choking on the intra-token split:
```
inte&
    &ger :: i
```
```
pr&
&i&
        &nt *, i
```

There is even this comment in flint:
```
116                     # TODO: With no matching &, some care is needed to align    
117                     # the whitespace correctly.  A job for another day!         
```
Perhaps that day has come...

Best I can see, the others are coming out correctly. `i = 5` is being incorrectly tagged as an implicit statement, but I reckon that's unrelated to this issue.

----

`flint parse lc`, with `use_str_as_token = True` in `__init__.py`.
```
lc/line_continuation_01.f90 (lc/lc/line_continuation_01.f90)

P: program line_continuation_01 
I: implicit none
D: integer :: i
I: i = 5
E: if ( i < 4 ) print * , i
E: if ( i > 4 ) print * , i
E: if ( i > 4 ) print * , i
E: if ( i > 4 ) print * , i
P: end program
```

```
lc/line_continuation_02.f90 (lc/lc/line_continuation_02.f90)

P: program line_continuation_02 
I: implicit none
D: integer :: j
D: integer :: k
E: inte ger :: i
E: i = 5
E: pr i nt * , i
E: print * , "some string is continued"
E: print * , "some string can contain & as a regular character is continued"
E: print * , "Even here: && <- there will be two &"
E: print * , i
E: print * , i
E: print * , i
E: print * , "some string is continued"
P: end program
```
```
lc/line_continuation_03.f90 (lc/lc/line_continuation_03.f90)

P: program line_continuation_03 
I: implicit none
D: integer :: i
D: integer :: k
I: i = 5
E: print * , i
E: print * , "some string is continued"
E: print * , "some string can contain & as a regular character is continued"
E: print * , "Even here: && <- there will be two &"
E: print * , i
E: print * , i
E: print * , i
E: print * , "some string is continued"
P: end program
```

**Comment by certik** [comment]
I know I had to spend time fixing this in LFortran also.

**Comment by marshallward** [comment]
The latest commit addresses this issue, and appears to be correct.  From the commit log:

> This patch adds support for line continuation tokens inbetween semantic tokens.  The block is triggered when `&` tokens appear at the end of a line and the beginning of the next, and there is no whitespace before the first & or after the second &.
> 
> When this occurs, the two tokens are concatenated into a single token, then passed through the Tokenizer parse() function, where they either form a new token or split back into two separate tokens.

I was able to utilize the new whitespace `tail` feature to avoid some of the harder cases.  But the trickiest was when the line continuation happened exactly at a token boundary with no whitespace between, e.g.:
```
integer&
       &::x
```
In this case, I was forced to restitch `integer::` back into a single token, then re-parse it through the tokenizer to split into `['integer', '::']`.  This works, but feels very inefficient, and I reckon it would be better to resolve line continuations when constructing the tokens, rather than inside the iterator serving the statements.

New output below.
```
lc/line_continuation_02.f90 (lc/lc/line_continuation_02.f90)
P: program line_continuation_02 
I: implicit none
D: integer :: j
D: integer :: k
D: integer :: i
I: i = 5
E: print * , i
E: print * , "some string is continued"
E: print * , "some string can contain & as a regular character is continued"
E: print * , "Even here: && <- there will be two &"
E: print * , i
E: print * , i
E: print * , i
E: print * , "some string is continued"
P: end program
```
lc/line_continuation_03.f90 (lc/lc/line_continuation_03.f90)
```
P: program line_continuation_03 
I: implicit none
D: integer :: i
D: integer :: k
I: i = 5
E: print * , i
E: print * , "some string is continued"
E: print * , "some string can contain & as a regular character is continued"
E: print * , "Even here: && <- there will be two &"
E: print * , i
E: print * , i
E: print * , i
E: print * , "some string is continued"
P: end program
```
lc/line_continuation_01.f90 (lc/lc/line_continuation_01.f90)
```
P: program line_continuation_01 
I: implicit none
D: integer :: i
I: i = 5
E: if ( i < 4 ) print * , i
E: if ( i > 4 ) print * , i
E: if ( i > 4 ) print * , i
E: if ( i > 4 ) print * , i
P: end program
```

**Comment by certik** [comment]
Yes, in fact I think this doesn't work well in LFortran either --- I couldn't figure out how to hook it up in the tokenizer for the same reason you found. So there is a phase before even tokenizing that polishes the code and takes care of this.

A robust Fortran parser thus might consists of:

1. Pre-tokenizing phase: take care of &, perhaps other things
2. Tokenizing: determine token types based on regex (or equivalent such as re2c or hand tokenizer)
3. Pre-parsing: determine with certainty the token types by keeping track of the context and looking ahead
4. Parsing: Can assume the token types are correct

**Comment by marshallward** [comment]
Closing this, but I think it was a very good example to identify the requirements of a generic tokenizer, and will shift these ideas to a discussion page.
