### ISSUE TITLE
other flint tools?

### ISSUE THREAD

**Issue by teuben** [marshallward/flint#12]
In our MIRIAD project we have a flint tool, where perhaps there are ideas that might be useful for you to check. It's written in C, and we used it to check out Fortran77 based code for the most obvious mistakes that the compiles (at the time) didn't catch.
I noticed the most recent gfortran-10 compiler is getting ahead (in some areas) of what our flint can do.

So, not an issue, just a comment.

https://github.com/astroumd/miriad/blob/master/src/tools/flint.c

**Comment by marshallward** [comment]
Thanks very much for mentioning this (and a reminder that it's far from an original name :rofl:).

I agree that the compilers are getting much better at reporting the sort of things.  I think the value that is emerging from this tool is its ability to analyze the things which compilers deliberately ignore, such as whitespace, case sensitivity, or generally style guide rules.

There's a long way to go but recent progress is encouraging. I will add your project to the list started [here](https://github.com/marshallward/flint/discussions/9), and will try to have a play with it at some point.
