### ISSUE TITLE
Index error in parse_header

### ISSUE THREAD

**Issue by aekiss** [marshallward/flint#16]
Hi Marshall

When I try parsing the MOM5 source I get
```
  File "/Users/andy/Documents/COSIMA/github/mom-ocean/flint/flint/units/unit.py", line 191, in parse_header
    self.name = line[utype_idx + 1]
IndexError: list index out of range
```
here
https://github.com/marshallward/flint/blob/7683da4ae45495c00875430a0cce74a63dfffc51/flint/units/unit.py#L191

This occurs when `line = ['end', 'interface']` with `self.utype`='interface', so `utype_idx` = 1

Should this be
```
 self.name = line[utype_idx]
```
?

**Comment by marshallward** [comment]
That seems right, I will try to have a look if I get some time.

I recently swapped over to a new lexer which handles whitespace differently so it's possible that the +1 was to account for whitespace which is no longer present.  (It's now tracked as part of the token.)

**Comment by marshallward** [comment]
`main` appears to use the old lexer, so it may be something else.

**Comment by marshallward** [comment]
I just tested this, it looks like it is failing because the interface block is unlabeled.
```
interface
    subroutine foo
        ...
    end subroutine foo
end interface
```
I have to admit that I don't even know what this is trying to do.

Anyway, I don't believ ethis is just an off-by-one error, but rather an handled case.

**Comment by marshallward** [comment]
Some more information about the underlying problem:
```
E:    interface
E:       subroutine right_hand_side_ppdd(first,numc,nlev,cc,pp,dd)
E:          logical, intent(in)                  :: first
E:          integer, intent(in)                  :: numc,nlev
E:          real(kind=8), intent(in)                 :: cc(1:numc,0:nlev)
 : 
E:          real(kind=8), intent(out)                :: pp(1:numc,1:numc,0:nlev)
E:          real(kind=8), intent(out)                :: dd(1:numc,1:numc,0:nlev)
S:       end
```
It does not even acknowledge that it has entered an `interface` block.  After that, it enters a new subroutine block, but does not realize it.  It then reaches the `end` of this internal subroutine, and thinks it is the end of the actual, parent subroutine, `ode_solver`.

So I think the main issue is that it is not recognizing these blocks.  I'd suggest we try to fix this before making them parse correctly.  For starters, I think we need to explicitly look for interface blocks inside of subroutine definitions.

**Comment by marshallward** [comment]
This is now fixed in the `use_f90lex` branch, along with a large number of other fixes and features.

The issue was very minor, somehow the `implicit none` check was made nonsense which threw all of the other parsing into a death spiral.
```

There is some behavior

**Comment by marshallward** [comment]
This has now been fixed in the `use_f90lex` development branch.

-            elif line[0] in 'implicit':
+            elif line[0] == 'implicit':

Once the output can be molded to resemble the form in `main` ("reformatted"), then I will close this issue.

**Comment by marshallward** [comment]
Subroutines within interfaces no longer cause propagating errors, mostly because interfaces are now handled independently of program units.
