### ISSUE TITLE
can't parse MOM5

### ISSUE THREAD

**Issue by aekiss** [marshallward/flint#4]
Hi @marshallward, I'm having difficulties updating the MOM5 diagnostics list following [these instructions](https://github.com/COSIMA/access-om2/wiki/Technical-documentation#MOM5-diagnostics-list). I've cloned the latest [MOM5](https://github.com/mom-ocean/MOM5) and Flint and made a script `parse.py` 
```
from flint.project import Project
proj = Project(verbose=True)
proj.parse('../MOM5/src/mom5')
```
which I put in the `flint` directory arranged like so
```
.
├── MOM5
│   ├── LICENSE
│   ├── README
│   ├── README.md
│   ├── bin
│   ├── data
│   ├── doc
│   ├── exp
│   ├── src
│   └── test
└── flint
    ├── README.rst
    ├── flint
    ├── out
    ├── parse.py
    ├── test
    └── tools
```
but `python3 parse.py > out` fails with
```
Traceback (most recent call last):
  File "parse.py", line 4, in <module>
    proj.parse('../MOM5/src/mom5')
  File "/Users/andy/Documents/COSIMA/github/mom-ocean/flint/flint/project.py", line 37, in parse
    f90file.parse(fpath)
  File "/Users/andy/Documents/COSIMA/github/mom-ocean/flint/flint/source.py", line 70, in parse
    unit.parse(flines)
  File "/Users/andy/Documents/COSIMA/github/mom-ocean/flint/flint/units/unit.py", line 139, in parse
    self.parse_header(lines.current_line)
  File "/Users/andy/Documents/COSIMA/github/mom-ocean/flint/flint/units/unit.py", line 175, in parse_header
    self.name = line[utype_idx + 1]
IndexError: list index out of range
```

If it's any help, `tail -20 out` yields
```
X: return
X: end function rho_feistel
M: end module eqstate
../MOM5/src/mom5/ocean_param/gotm-4.0/util/ode_solvers.F90 (../MOM5/src/mom5/../MOM5/src/mom5/ocean_param/gotm-4.0/util/ode_solvers.F90)
flint: unsupported preprocess directive: include"cppdefs.h"

[]
S: subroutine ode_solver ( solver , numc , nlev , dt , cc , right_hand_side_rhs , right_hand_side_ppdd )
I: implicit none
D: integer , intent ( in ) :: solver , nlev , numc
E: realtype , intent ( in ) :: dt
E: realtype , intent ( inout ) :: cc ( 1 : numc , 0 : nlev )
E: interface
E: subroutine right_hand_side_ppdd ( first , numc , nlev , cc , pp , dd )
E: logical , intent ( in ) :: first
E: integer , intent ( in ) :: numc , nlev
E: realtype , intent ( in ) :: cc ( 1 : numc , 0 : nlev )
E: realtype , intent ( out ) :: pp ( 1 : numc , 1 : numc , 0 : nlev )
E: realtype , intent ( out ) :: dd ( 1 : numc , 1 : numc , 0 : nlev )
S: end
```

AFAIKR we only made that diagnostics list once, a couple of years ago.

**Comment by marshallward** [comment]
I wish I could say that I was reproducing this, but I'm seeing even more severe errors, including undefined variables.

I think unfortunately you've hit me at a bad time when I was doing some work on this to try and handle docstrings, when I should have been working on a dev branch.

I'll try to work my way up to your error, but it could take a bit longer than it should.

**Comment by marshallward** [comment]
This is currently just a guess, but it seems like this preprocessor is failing:
```
#include"cppdefs.h"
```
because there is no space between `include` and the include file.

These files are full of non-standard tokens which need to be defined by `cppedefs.h`.

I've also been working on the preprocessing more lately, and may have changed it to be more strict - perhaps too strict.

Now I would have assumed a space was needed here, but perhaps I am very wrong?

**Comment by marshallward** [comment]
`#include"cppdefs.h"` seems to be valid (or at least work in `cpp`).  So I need to fix this, sorry.

Will try to get it done soon.

**Comment by marshallward** [comment]
@aekiss  I pushed a change to master that appears to work for me.

**Comment by aekiss** [comment]
Brilliant, thanks @marshallward, I was just about to reply that it's not urgent, but you've already fixed it :-)
